### ISSUE TITLE
<bug> The specified file cannot be found (WinError 2)

### ISSUE THREAD

**Issue by AnkiGames** [manucabral/YoutubeMusicRPC#39]
# **Screenshots**
![image](https://github.com/manucabral/YoutubeMusicRPC/assets/131894815/e9eaad22-ede5-4aef-841f-cbe1e6df0a36)

# **Desktop:**
 - OS: Windows 11
 - Version: Pro 64 bits

# **Browser:**
 - Browser: Opera 124.0.6367.62

**Comment by manucabral** [comment]
> Could this be due to the fact that I use Vencord?

Hi,
It’s probably due to the system language since the program doesn't support multiple languages, but you could try using the [v0.5.1](https://github.com/manucabral/YoutubeMusicRPC/releases/tag/0.5.1) version.
I'm developing a new version that is compatible and more stable than the latest one. Thanks for reporting it.

**Comment by AnkiGames** [comment]
thx for the answer
